import Head from 'next/head';
import Image from 'next/image';

export default function NotFound() {
  return (
    <>
      <Head>
        <title>404 - Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>404 - page not found</h1>
      </main>
    </>
  );
}
